### ISSUE TITLE
Ten Quick Tips

### ISSUE THREAD

**Issue by cgreene** [Benjamin-Lee/deep-rules#1]
It would be helpful to make sure this ten simple rules gets distinguished from a ten quick tips article that got published last year:
https://biodatamining.biomedcentral.com/articles/10.1186/s13040-017-0155-3

**Comment by Benjamin-Lee** [comment]
Great find–I missed that paper. There is some overlap (_e.g._ minimize overfitting to prevent inflated accuracy scores) and we'll certainly cite the paper. I do think that there should be more discussion of deep learning focused rules (there isn't really any in that paper). While DL probably _shouldn't_ be the first ML approach people use, it often is–I know it certainly was for me and I completely botched it. If you think that the ten tips for ML paper is _too_ similar, we can pivot to focusing primarily on rules for DL in bio.

**Comment by Benjamin-Lee** [comment]
@cgreene what do you think? After a week of reflection, I'm leaning towards pivoting to focus on DL.

**Comment by cgreene** [comment]
I agree that to remain more unique from that other article, focusing on deep learning makes the most sense! Sorry - I have been traveling and I'm just getting re-engaged with this now!

**Comment by jmschrei** [comment]
I agree that this manuscript would be strongest if it focused on issues that are specific to deep learning and not machine learning in general. There have been many great suggestions already along the lines of "make sure you've motivated the need for deep learning," and I think that there is room for an impactful paper that focuses on that. Essentially, this paper might serve as a good resource for non-experts in ML who are wondering whether they should use "deep learning" in their project, and if so, how to properly apply it.

**Comment by SiminaB** [comment]
Just leaving this here for a somewhat overlapping perspective, so that I don't open a new issue https://twitter.com/atulbutte/status/1062160867272220672

**Comment by AlexanderTitus** [comment]
This has been agreed upon and is in process.
