### ISSUE TITLE
Always compare the performance of DL models with simple baseline models

### ISSUE THREAD

**Issue by khyu** [Benjamin-Lee/deep-rules#10]
Depending on the amount of available data and the type of tasks, DL models may not be the best performing one. For example, the Supplemental Materials of Rajkomar A et al. (2018) (https://www.nature.com/articles/s41746-018-0029-1) indicated that their simple baseline models had achieved performance comparable with that of DL in a number of tasks, which may be a surprise to many.

**Comment by fmaguire** [comment]
Covered in Tip 2: https://github.com/Benjamin-Lee/deep-rules/blob/master/content/04.baselines.md
