### ISSUE TITLE
Fine-tune the baseline models before concluding they are worse than DL

### ISSUE THREAD

**Issue by khyu** [Benjamin-Lee/deep-rules#11]
Related to [#10](https://github.com/Benjamin-Lee/deep-rules/issues/10), many conventional machine learning methods (e.g., support vector machines, random forests) require parameter tuning. Before jumping to the conclusion that DL is better than other machine learning methods, investigate whether the baseline models are fine-tuned.

**Comment by beamandrew** [comment]
+1 for having strong, non-strawman baselines.

**Comment by fmaguire** [comment]
Covered in Tip 2: https://github.com/Benjamin-Lee/deep-rules/blob/master/content/04.baselines.md
