### ISSUE TITLE
Suggest tip #9 wording change 

### ISSUE THREAD

**Issue by chevrm** [Benjamin-Lee/deep-rules#114]
Tip 9: Interpret predictions in the correct manner

For me, "correct" is a little absolute. Maybe something more along the lines of "Interpret predictions carefully" or something similar.

Thoughts?

**Comment by agitter** [comment]
I agree.  And based on the various issues mapped to this tip in `tips.md`, interpret can mean more than one thing.

`Don't overinterpret predictions` could be another phrasing, or did you have something else in mind in #30?

**Comment by Benjamin-Lee** [comment]
Tagging @SiminaB @blengerich and @khyu since y'all have also contributed to the discussion around tip 9.
