### ISSUE TITLE
Understand the biomedical questions

### ISSUE THREAD

**Issue by khyu** [Benjamin-Lee/deep-rules#13]
There are a large number of prediction tasks DL algorithms can do. However, many of them may not be clinically useful or may be confounded by factors in the current clinical practice. For example, in any retrospective study with AP view (usually for bed-ridden patients) and PA view chest X-ray images, it would not be surprising the DL identifies that AP view images are correlated with poorer clinical outcomes, due to confounding by indication.

**Comment by fmaguire** [comment]
Mentioned in https://github.com/Benjamin-Lee/deep-rules/blob/master/content/06.know-your-problem.md

> Systematic biases, which can be induced by confounding variables, for example, can lead to artifacts or so-called "batch effects." As a consequence, models may learn to rely on correlations that are irrelevant in the scientific context of the study and may result in misguided predictions and misleading conclusions [@doi:10.1038/nrg2825]. Other study design considerations that should not be overlooked include knowing whether a study involves biological or technical replicates or both. For example, are some samples collected from the same individuals at different time points? Are those time points before and after some treatment? If one assumes that all the samples are independent but that is in fact not the case, a variety of issues may arise, including having a lower effective sample size than expected.
