### ISSUE TITLE
Send presubmission inquiry to PLOS Comput Bio

### ISSUE THREAD

**Issue by Benjamin-Lee** [Benjamin-Lee/deep-rules#14]
I drafted a [presubmission inquiry](https://github.com/Benjamin-Lee/deep-rules/blob/master/content/presubmission_inquiry.md) that we'll send in once we have a full ten rules proposed. 

Feedback from anyone would be highly appreciated. We can always change the rules and their ordering, but we should get this in and hear that PLOS is interested before doing any big publicity effort (just in case PLOS isn't happy about the idea).

@cgreene @agitter Did you do a presubmission inquiry for the deep review and, if so, do you have any feedback with respect to this one?

**Comment by Benjamin-Lee** [comment]
For reference, although not targeted towards ten simple rules articles: [10.1371/journal.pcbi.1004098](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1004098)

**Comment by agitter** [comment]
@cgreene was approached by the journal first about writing a headline review so deep review did not require a pre-submission inquiry.

Your draft letter looks like it is on the right track, though I didn't read or edit carefully.  I agree it is a good idea to have some consensus about most of the 10 rules before sending the letter.

**Comment by Benjamin-Lee** [comment]
@agitter  then would it then make more sense to publicize the repo *first* in order to get a consensus on the rules, rather than waiting to hear back from the editor?

**Comment by agitter** [comment]
Advantages of publicizing first:
- Showing broad community interest and a strong list of rules could help the presubmission inquiry
- If the article is slow to write, reduces the time between presubmission and full submission
- Even a successful presubmission inquiry doesn't ensure publication at PLOS Computational Biology, so recruiting others who are interested in writing a short practical advice manuscript (independent of the eventual journal and format) may be more realistic

Advantages of presubmission inquiry first:
- If approved, it would help draw interest to the manuscript
- If you or others are only interested in writing this for PLOS Computational Biology (and not other journals), it would be good to know as soon as possible whether that is feasible

@Benjamin-Lee those are my thoughts.  Is there anything I missed?

**Comment by Benjamin-Lee** [comment]
@agitter I am by no means obligated to PLOS Computational Biology. Other journals clearly (#1) accept Ten Simple Rules style articles, so it's not as if this project couldn't be submitted elsewhere.

Unless any of the contributors feels otherwise, it seems like publicizing first is the way to go. Thanks again @agitter for the insight!
