### ISSUE TITLE
Distinguishing this project from other review papers

### ISSUE THREAD

**Issue by lykaust15** [Benjamin-Lee/deep-rules#165]
As we know, there are a lot of other review papers available. Should we write a paragraph in the introduction part to distinguish this project from the other reviews and cite those papers properly for the readers' reference? Furthermore, we can emphasize the contribution and the characteristic of this manuscript in that paragraph. Sometimes the reviewer will ask for this kind of questions, which I have encountered when submitting the previous review papers. Currently, the introduction of this manuscript is very straightforward and only a few review papers are mentioned.

**Comment by agitter** [comment]
The intended differentiating factor of this project is that:
> a lack of concise recommendations for biological applications of DL hamper newcomers wishing to apply state-of-the-art DL in their research

Does that need to be further emphasized?

We can strategically cite some review articles that serve a specific purpose, but I don't think we need to cite all reviews on deep learning in biology.  There must be at least 20 or 30 of them.

**Comment by AlexanderTitus** [comment]
I agree, as this is not a true review in itself. It’s tempting to add everything, but as you say, the distinguishing factor here is concise recommendations rather than comprehensive review.

**Comment by lykaust15** [comment]
Thank you for the clarification. There are indeed at least 30 of them. I think we do not necessarily include all of them but 2 or 3 for the reader's reference, pointing them to the perspective of using deep learning in biology. Currently, there is only one of them: 'Opportunities and obstacles for deep learning in biology and medicine', which is devoted to both biology and medicine. I guess we should focus more on "biology", as indicated by the title?

**Comment by rasbt** [comment]
I don't think that it is necessary to compare and contrast it with existing review papers because it doesn't aim to be a classic review paper. However, we could cite existing review papers in a way that is beneficial for the reader. I.e., we could pick one or two of the most comprehensive & recent review papers and refer to it as a useful resource for an overview of biological problems being solved/tackled by DL

**Comment by lykaust15** [comment]
@rasbt Yes, I agree with your idea.
