### ISSUE TITLE
If you don't have enough data, don't even start

### ISSUE THREAD

**Issue by hugoaerts** [Benjamin-Lee/deep-rules#17]
This is, surprisingly, a very reoccurring problem. People spend a lot of time on analyzing small datasets, just as a proof-of-principle. However, the data are too small, no independent validation, etc to derive any meaningful results. Not enough data -> do something else

**Comment by beamandrew** [comment]
I think this needs more nuance. How much is "enough" data? What about things like transfer learning that can help if you don't have enough data to train from scratch?

**Comment by hugoaerts** [comment]
Yes, I agree. But it is almost impossible to specify exactly what is 'enough' as this depends on several factors and will be different for almost every case. For example for training it depends on several aspects: complexity of network, which layers are retrained (transfer learning or not), your tuning set performance, difficulty of the classification/prediction problem, etc. For the testing dataset(s) this often comes down to statistics and power calculations: what is the expected effect size, event ratio of all classes, balance between training/tuning/test datasets, etc. 

As we can't give a hard number, I think we can address the following: a lot of investigators know before they even start that their datasets are too small. They then say this is an "exploratory analysis" or "proof-of-principle" and even get these published in decent journals. However, these investigations are often worthless and don't add anything useful to the field. When confronted with such a problem, I often advise people to continue to look for another problem/dataset.

**Comment by agitter** [comment]
There was also some good discussion of these ideas in #5.  Should we merge the discussion threads?

**Comment by Benjamin-Lee** [comment]
Let's merge this with #5 and possibly #3. I think we're hitting on the same idea of deep learning + insufficient data = bad science.

The difference #3 and #5/#17 is that, even with a sufficient amount of data, deep learning still is not always the best approach; without sufficient data, deep learning almost certainly is not the best approach.
