### ISSUE TITLE
Define the research questions, curate the data, and specify the analysis strategies before looking at the data.

### ISSUE THREAD

**Issue by hugoaerts** [Benjamin-Lee/deep-rules#18]
Before diving into the data and starting an 'exploratory' analyses; first, simply think about what you want to do and what strategy you would like to take. This will narrow your analysis options, hopefully reducing false findings.

**Comment by fmaguire** [comment]
Mentioned in: https://github.com/Benjamin-Lee/deep-rules/blob/master/content/06.know-your-problem.md

> Having a well-defined scientific question and a clear analysis plan is crucial for carrying out a successful deep learning project. Just like it would be inadvisable to step foot in a laboratory and begin experiments without having a defined endpoint, a deep learning project should not be undertaken without preparation.
