### ISSUE TITLE
addition to tip 12 text

### ISSUE THREAD

**Issue by SonjaAits** [Benjamin-Lee/deep-rules#188]
It could be nice to add a few examples to the tip 12 text of the types of data which are problematic, e.g. datasets from the medical domain (clinical records, genetic data, etc).

**Comment by SiminaB** [comment]
Hi Sonja! Do you mean tip 10/section 12? https://github.com/Benjamin-Lee/deep-rules/blob/master/content/12.privacy.md
I think we decided it would be focused on biology, not medicine, though we can probably mention clinical records given that the topic is privacy. Please feel free to add examples and open up a pull request. :-)

**Comment by Benjamin-Lee** [comment]
Just to bump this back to the top of peoples minds, do we want to add some concrete examples to tip 10? I'm in favor of it since it will make the paper more concrete.
