### ISSUE TITLE
Review: Opportunities and obstacles for deep learning in biology and medicine

### ISSUE THREAD

**Issue by SonjaAits** [Benjamin-Lee/deep-rules#189]
Good review to cite
https://doi.org/10.1098/rsif.2017.0387

**Comment by agitter** [comment]
Closing this because we have this reference (https://benjamin-lee.github.io/deep-rules/v/cb7f6a177d5ad63b28daec691f545b6df611a55f/#ref-PZMP42Ak)

I'm glad you like the review.  Several of us involved in this project were also authors of that review.
