### ISSUE TITLE
Propose ten rules

### ISSUE THREAD

**Issue by Benjamin-Lee** [Benjamin-Lee/deep-rules#2]
To get this project started, we're going to need to have an initial idea of ten rules to send to PLOS as a presubmission inquiry. 

I propose the following:

1. Don't use deep learning if you don't have to.
2. Don't share model weights trained on private data.
3. When it comes to data, size matters.
4. Use existing model architectures whenever possible.
5. Normalize, normalize, normalize

**Comment by agitter** [comment]
@Benjamin-Lee if you anticipate the need to debate and discuss each rule, you could consider creating a new issue for each candidate rule and using a `rule` label to organize them.

**Comment by Benjamin-Lee** [comment]
@agitter Thanks for the suggestion! On it now
