### ISSUE TITLE
Lock testing cohorts and only evaluate a trained model once. 

### ISSUE THREAD

**Issue by hugoaerts** [Benjamin-Lee/deep-rules#20]
This is probably the most occurring mistake. A lot of people test-test-test and test different models on the same testing cohorts, and then only report the best performing model. The deep learning model is, of course, over fitted. The tuning datasets can be used more frequently, but the testing should be locked and not used before the final model is identified

**Comment by fmaguire** [comment]
Covered in pull request, can be closed when/if merged.

**Comment by rasbt** [comment]
Just added a "Fixes" in the PR to auto-close this one then.

**Comment by fmaguire** [comment]
Ah cool, didn't actually know about that github feature.
