### ISSUE TITLE
Update thumbnail

### ISSUE THREAD

**Issue by vincerubinetti** [Benjamin-Lee/deep-rules#201]
Hello Manubot user.

If you were not already aware, your paper is being showcased in the [Manubot Catalog](https://manubot.org/catalog/).

Previously, we were making our own thumbnails for each paper, and hosting them in the same repository as `manubot.org`. But now we are moving to a system of having each paper store its thumbnail in its own repository, and linking to it from there.

Here is our suggested thumbnail for your paper that follows the new [thumbnail guidelines](https://github.com/manubot/catalog#thumbnail-guidelines):

![New Project](https://user-images.githubusercontent.com/8326331/64824922-7e6fc200-d589-11e9-8df1-2673996cce9b.png)

Please place this image *in the root of your repository* with the name `thumbnail.png`. Once you have, let us know in this issue and we'll do the rest to update the catalog.

**Comment by Benjamin-Lee** [comment]
Done!
