### ISSUE TITLE
Garson's algorithm TODO

### ISSUE THREAD

**Issue by Benjamin-Lee** [Benjamin-Lee/deep-rules#209]
In our black box rule, there is currently a TODO asking us to consider detailing Garson's algorithm. 

I did some thinking and have the following thoughts:

- Garson's algorithm hasn't fared well in empirical experiments: https://doi.org/10.1016/j.ecolmodel.2004.03.013 ([pdf](https://depts.washington.edu/oldenlab/wordpress/wp-content/uploads/2013/03/EcologicalModelling_2004.pdf))
- It's nearly impossible to find the original paper. I tried everything. The DOI doesn't point to anything (search on Google; the only hits are the ACM page and this paper) and I couldn't find it in the Harvard library or Sci-Hub.
- I'm not sure we should spend the space in our paper describing algorithms in any detail, particularly ones whose usefulness in comparison to others is in question.

I suggest including a reference to a recent overview of DL interpretability for further reading. We could cite this paper ([arXiv:2001.02522](https://arxiv.org/abs/2001.02522)) and/or this freely available book (https://christophm.github.io/interpretable-ml-book/). I would prefer to cite the latter if at all possible, since it is also following the model of open-source collaborative writing that we are. Another advantage of the book _Interpretable Machine Learning_ is that it contains links to code (usually in R and Python) for each of the methods it describes. I prefer to outsource the recommendation of actual software libraries to a living document (rather than a static paper such as this) so that it will retain its usefulness for longer. 

I'll prep a PR with my suggestions in the coming days but would love to hear @tbrittoborges's thoughts on the matter.

**Comment by rasbt** [comment]
> I suggest including a reference to a recent overview of DL interpretability for further reading. We could cite this paper (arXiv:2001.02522) and/or this freely available book (https://christophm.github.io/interpretable-ml-book/). 

Why not recommending and referring to both?

**Comment by tbrittoborges** [comment]
I will follow this up later today.

**Comment by Benjamin-Lee** [comment]
> > I suggest including a reference to a recent overview of DL interpretability for further reading. We could cite this paper (arXiv:2001.02522) and/or this freely available book (https://christophm.github.io/interpretable-ml-book/).
> 
> Why not recommending and referring to both?

I'm happy to reference both. Working on a quick PR now.

**Comment by tbrittoborges** [comment]
I agree that both references are relevant, and that Fan et all is particular good as a tip.
However, I would like discuss a few points @Benjamin-Lee last PR #212

**Comment by Benjamin-Lee** [comment]
@tbrittoborges sounds good. I won't merge #212 until you comment on it.

**Comment by Benjamin-Lee** [comment]
@tbrittoborges I added some comments so let me know what you think.

**Comment by Benjamin-Lee** [comment]
Ok I rewrote the last sentence. Can I get some fresh reviews (maybe @tbrittoborges and/or @rasbt)?
