### ISSUE TITLE
Do we need both Travis and GH Actions?

### ISSUE THREAD

**Issue by Benjamin-Lee** [Benjamin-Lee/deep-rules#222]
I just noticed we're using both. Is it safe to delete the Travis config since we're using GH actions?

**Comment by cgreene** [comment]
yup

**Comment by Benjamin-Lee** [comment]
I realized this was a terrible writeup. The issue title and the question in the body ask opposite questions. Which is the answer for?

**Comment by cgreene** [comment]
It should be safe to delete the travis config, or, even better, just disable travis in their settings so that you don't create a conflict with rootstock if you ever update the document.

**Comment by Benjamin-Lee** [comment]
Got it, just disabled Travis.

**Comment by dhimmel** [comment]
Just seeing this. No need for travis if you're using GitHub Actions. Looks like you found a good solution. 

Disabling travis or removing the travis config work. Some more information in the setup docs at https://github.com/manubot/rootstock/blob/0964fd7ed7fdc1e3b468b5f4f1234d24de0b14fc/SETUP.md#github-actions.
