### ISSUE TITLE
Rename Tip 1 to "Decide if deep learning may be appropriate for your problem"

### ISSUE THREAD

**Issue by ejfertig** [Benjamin-Lee/deep-rules#228]
I find the comment "Those developing deep learning models should select datasets that are relevant to the problem at hand; non-salient data can hamper performance or lead to spurious conclusions." unclear. How can someone determine if they have the right dataset? Does this mean in terms of sample size or something else? Some clear examples would help.

**Comment by ejfertig** [comment]
Also, as a further comment to this -- there appears to be some overlap between the dataset selection w/in tip 1 and the tip 4 know your data. Would help to streamline and clarify the differences in the points on data selection in these two tips.

**Comment by cgreene** [comment]
This is a good point - particularly as it relates to transfer learning and/or domain adaptation.

**Comment by Benjamin-Lee** [comment]
@cgreene what do you think about moving the content that overlaps in tip 1 to each respective tip (overfitting and know your data, etc) and then subbing in the "decide if DL is right for your problem" tip you proposed here: https://github.com/Benjamin-Lee/deep-rules/pull/225#pullrequestreview-500191626

**Comment by cgreene** [comment]
Yea - I think I really like this. Tip 1 could be "Decide if deep learning may be appropriate for your problem" and then the rest of the text moves. That tip could contain the current sentiment of tip 1. 👍

**Comment by ejfertig** [comment]
Agreed. I think it would be really helpful to define different flavors of deep learning here and how you can select between models for specific problems. How can you use DL in a supervised context? Unsupervised? When would DL be the best choice?

**Comment by Benjamin-Lee** [comment]
@cgreene Do you think you could work together with me to get the rewrite done by the end of the week, which is the original deadline for freezing changes (#226)? We could also push the deadline back, though I hate to prolong things even more. 

Either way, I can make a PR moving the content and renaming the first tip to get started on this process. @pstew, @agitter, and @rasbt, what do you think of this idea?

**Comment by ejfertig** [comment]
I can help with editing and a view fOr clarity from the non DL perspective if it’s helpful.

**Comment by agitter** [comment]
> what do you think of this idea?

I have other deadlines this week so I'm not sure I'll be able to spend much time here.  Please feel free to made edits as you'd like.

**Comment by Benjamin-Lee** [comment]
@agitter, understood. Would pushing back another week be better for your schedule? I'm not trying to rush things, just to keep up the momentum.

**Comment by agitter** [comment]
It may not make a difference.  You have some good momentum now, so I'd say keep it going.

**Comment by rasbt** [comment]
I am in the same boat as @agitter (and there are midterms this week). I would be happy to & able to review the paper at towards the end of the week or by next week. By "reviewing" I mean making a full pass and provide feedback or suggest some final edits.
