### ISSUE TITLE
Project organization

### ISSUE THREAD

**Issue by agitter** [Benjamin-Lee/deep-rules#23]
@Benjamin-Lee I had a few big picture ideas for this collaborative manuscript based on our deep review experience.

In addition to the ideas in the readme about how participants can contribute, which should remain short like they are now, you could consider a more expansive contributing document.  That would outline authorship criteria or other expectations for the collaborative project.  See the deep review [example](https://github.com/greenelab/deep-review/blob/master/CONTRIBUTING.md).

That would also be a good place to include a code of conduct, which we did not have in deep review but now [recommend](https://greenelab.github.io/meta-review/#limitations) for Manubot-based projects.

**Comment by agitter** [comment]
One more thought is that it is easy to determine who directly contributed to the manuscript through GitHub's contributors page or the git log. However, if you want to acknowledge participants who joined in the discussion but did not meet all of the authorship criteria, it may be easiest to keep a running log of them now.  It can be arduous to comb through issues and recreate it later.

**Comment by Benjamin-Lee** [comment]
@agitter, thank you for the insightful recommendations. Adding the contributing document now.
