### ISSUE TITLE
Second person or third person?

### ISSUE THREAD

**Issue by Benjamin-Lee** [Benjamin-Lee/deep-rules#237]
Throughout the manuscript, we use a mix of different points of view, probably reflecting the various authors who wrote each line. Before submitting, I suggest we settle on one and modify the manuscript accordingly. Based on looking at various other Quick Tip articles, I think we should go with second person though I don't have a particularly strong opinion.

## Second Person
- https://doi.org/10.1371/journal.pcbi.1008090
- https://doi.org/10.1371/journal.pcbi.1007433
- https://doi.org/10.1371/journal.pcbi.1007222
- https://doi.org/10.1371/journal.pcbi.1006907
- https://doi.org/10.1371/journal.pcbi.1006959
- https://doi.org/10.1371/journal.pcbi.1006906
- https://doi.org/10.1371/journal.pcbi.1006472
- https://doi.org/10.1371/journal.pcbi.1006542

## Third Person
- https://doi.org/10.1371/journal.pcbi.1007449
- https://doi.org/10.1371/journal.pcbi.1007358
- https://doi.org/10.1371/journal.pcbi.1007434
- https://doi.org/10.1371/journal.pcbi.1006750

**Comment by rasbt** [comment]
I agree that we should decide this so that we can edit the manuscript more productively in the upcoming days. Generally, I prefer 3rd person, but I think Quick Tip articles are generally more informal and 2nd person would probably be okay here. I would slightly favor third person but please go ahead with 2nd person if no one else has a strong opinion on that.

**Comment by cgreene** [comment]
I have a slight preference for third person + royal we because it's more natural for scientific writing for me, but not a strong preference.

**Comment by pstew** [comment]
I may be guilty of not using it in a commit, but I am on board with third person.

**Comment by Benjamin-Lee** [comment]
Ok third it is

**Comment by agitter** [comment]
Closed by #357
