### ISSUE TITLE
Replace i.e. and e.g. with plain English

### ISSUE THREAD

**Issue by Benjamin-Lee** [Benjamin-Lee/deep-rules#260]
I suggest using commas and italics. It doesn't really matter so long as we're consistent.

**Comment by betsig** [comment]
Going through this now.

Couple of questions: 
We define DL as the acronym for 'deep learning' , but throughout the paper use both 'deep learning' and 'DL'. Is there a preferred way to keep the use of these consistent?
We use (for example, ...) multiple times... should these all be changed to (_e.g._, ...)?

**Comment by rasbt** [comment]
While I always use I always use abbreviations like e.g., etc., and i.e., in informal settings (like social media & email), my (personal) preferences for professional writings are:

-  I sometimes use "e.g.," during drafting but eventually replace it with "for example," later if there are no page or space constraints.
- Same as above for "i.e.," vs "for instance," and  ", etc." and ", and others"

The Chicago Manual of Style-based "A Manual for Writers of Research Papers, Theses, ..." and Chicago Manual of Style itself states that it is better to spell common abbreviations like i.e. and e.g. out and if they are used, they should be

> confined to parentheses and notes and followed by a comma.

**Comment by Benjamin-Lee** [comment]
Ok @rasbt let's do that.

**Comment by betsig** [comment]
Okay, makes sense, but I'm 99% sure there weren't any abbreviations outside parentheses. There were a couple of instances where for example was used within  parenthesis like:

> While performance baselines available from existing literature also serve as a helpful guidance and should be taken into account, an implementation of a simple model (for example, linear or logistic regression) using the same software framework planned for DL is additionally helpful for assessing the correctness of data processing and performance evaluation pipelines.

My question was if we should change these to (_e.g._, linear or logistic regression), which we have used in other sections.

**Comment by rasbt** [comment]
> My question was if we should change these to (e.g., linear or logistic regression), which we have used in other sections.

Personally, I would change it to "(for example, ...)" in formal writing, even if it is in parentheses. But "e.g.," would be okay. What do others think?

**Comment by Benjamin-Lee** [comment]
I have no opinion when choosing between synonyms. If @rasbt prefers "(for example, ...)" then so be it.

**Comment by rasbt** [comment]
As you said at the beginning,

>  It doesn't really matter so long as we're consistent.

but

> prefers "(for example, ...)" then so be it.

I think is that's reasonable since we don't have any page limits yet, and I think adopting professional style guides isn't a bad idea :)

**Comment by Benjamin-Lee** [comment]
@rasbt, @betsig PRed this fix in #263. Can you review?
