### ISSUE TITLE
Rephrase "anthropomorphize the models" for clarity 

### ISSUE THREAD

**Issue by Benjamin-Lee** [Benjamin-Lee/deep-rules#268]
What does it mean to "anthropomorphize the models?" I know the meaning of the term and it's application as a literary device, but not sure of its exact meaning here...

_Originally posted by @SiminaB in https://github.com/Benjamin-Lee/deep-rules/pull/241#r503038700_

**Comment by fmaguire** [comment]
This is has now been rephrased so I'm closing the issue.
