### ISSUE TITLE
Proposal: Presubmission inquiry to Nature Computational Science

### ISSUE THREAD

**Issue by Benjamin-Lee** [Benjamin-Lee/deep-rules#270]
Hi everyone!

Today I came across some important news: [Nature Computational Science](https://www.nature.com/natcomputsci), a new journal dedicated to multidisciplinary computational research, is launching in January 2021.

Notably, they have a review/perspective article format that I think our paper, with minor modifications, might be a good fit for. Here are a few key advantages:

- Because we would likely be in their first issue(s), it would lend greater visibility and readership to our paper—Nature is well known to help increase traffic to papers via social media and public mentions, especially across disciplines.
- Since the journal is new, its structure and style are likely flexible and open to creativity.
- Most of our sections are of relevance to other disciplines, not just biology.
- It would be advantageous for us to build a relationship with the editors now, as early movers, before the journal become crowded with inquiries; relationship might help us to publish additional articles and/or be featured in the future.

Therefore, I suggest that we send a pre-submission inquiry to this new journal. If they’re interested, we could modify and submit our article to them. If rejected, we could still submit it to PLOS Computational Biology as our back-up. What do collaborators here think about this strategic idea?

**Comment by rasbt** [comment]
I agree with all your points regarding Nature as a publisher and the potential upsides of being part of a new journal. Just looking at it though, I think they are looking more for actual methods papers. I.e., papers developing a particular method. This 10 tips article seems to be more of a mix between opinion and review paper (kind of like articles in "Current Opinion in ..." journals or maybe reviews fitting the Methods journal). However, I think that review-type of articles would likely be invite-only.

Then, there's the downside that this article probably wouldn't be substantive enough for reviewers not familiar with / expecting a 10 quick tips article.

While I find this new journal attractive, I am a bit doubtful that the current content we have would be a good fit. I'd be kind of worried that it could be a waste of time to submit there because they'd reject it. But maybe I am being pessimistic here. On the other hand, submitting a pre-submission inquiry doesn't hurt either, if you want to do that @Benjamin-Lee 

What do other people think?

**Comment by Benjamin-Lee** [comment]
I'm not sure either, which is why I think an inquiry is the best move. If they're interested, they'll let us know. I definitely wouldn't want to submit out of the blue since you're right that it may be a waste if time if they're not interested. I can get started drafting up a quick inquiry (based on what we sent to PLOS Computational Biology) and fire that off so we can hear what they have to say.

**Comment by agitter** [comment]
I see a 10 rules article as a specialized format that would take substantial reframing to transform into a perspective or review.  I also expect that this team has a good understanding of the relevant issues when applying deep learning in biology but may not know what a physicist or astronomer should be aware of.  I like writing to a specific and well-defined audience.

However, there isn't anything to lose by submitting a presubmission inquiry if @Benjamin-Lee and others are interested.  You already have a draft, and it wouldn't slow down the timeline in #226.

**Comment by pstew** [comment]
I would like to see how it fairs with PLOS before we start considering other journals. Given the content and the co-authors I think it will be very well received.

**Comment by rasbt** [comment]
> However, there isn't anything to lose by submitting a presubmission inquiry if @Benjamin-Lee and others are interested. You already have a draft, and it wouldn't slow down the timeline in #226.

If we were to do that, we should probably change the title though. Spontaneous though: "Dos and Don'ts of (/for) Deep Learning in Biological Research"

**Comment by chevrm** [comment]
agreed with rasbt...if we go somewhere else, the "N rules" title need not apply. That said, I also agree with pstew in that PLoS seems like the natural place to try first.

**Comment by Benjamin-Lee** [comment]
> I see a 10 rules article as a specialized format that would take substantial reframing to transform into a perspective or review. I also expect that this team has a good understanding of the relevant issues when applying deep learning in biology but may not know what a physicist or astronomer should be aware of. I like writing to a specific and well-defined audience.
> 
> However, there isn't anything to lose by submitting a presubmission inquiry if @Benjamin-Lee and others are interested. You already have a draft, and it wouldn't slow down the timeline in #226.

@agitter In this idea we'd be writing for the same target readers (biologists getting started in DL), which is important since a lot of the value added is the biological examples and focus. What I meant was that this article, if read by a computationally oriented chemist for example, would still be useful since it discusses topics like Continental Breakfast Included and model attacks which translate do to their domain. 

+1 on the timeline. Sending the inquiry should not be blocking for #226.

> > However, there isn't anything to lose by submitting a presubmission inquiry if @Benjamin-Lee and others are interested. You already have a draft, and it wouldn't slow down the timeline in #226.
> 
> If we were to do that, we should probably change the title though. Spontaneous thought: "Dos and Don'ts of (/for) Deep Learning in Biological Research"

I'm think that's a good idea since "Quick Tips" is a PLOS thing. We could use that as the title in the presubmission inquiry and then change it in the manuscript if we choose to go that way

**Comment by Benjamin-Lee** [comment]
Letter is sent!

**Comment by Benjamin-Lee** [comment]
Here's the response:

> Dear Dr. Lee,
>
>Thank you very much for your enquiry about submitting a manuscript to Nature Computational Science.
>
>I've now had a chance to discuss your work with my colleagues, and although we think that it sounds very interesting, we are still uncertain as to the degree to which the study provides practical, novel, and impactful guidelines to the community.
>
>Therefore, we would like to invite you to submit the full manuscript to Nature Computational Science so that we can examine >the data before deciding whether to send the paper out to review.
>
>If this is acceptable to you, you can submit the complete manuscript using the link below:
>
>[link redacted since it bypasses sign on]
>
>If you have any questions, please feel free to contact me.
>
>Best regards,
>
>Ananya Rastogi, PhD
>Associate Editor
>Nature Computational Science

Though I don't have a ton of experience with presubmission inquires, it doesn't appear to me that they're particularly interested given that they won't rule out a desk rejection. I'd appreciate it if one of the more senior authors would chime in with their opinion on the letter. Given the asymmetry in effort (it's easy for them to desk reject the paper but nontrivial for us to modify the paper for their venue) it seems to me that PLOS is a better venue.

**Comment by agitter** [comment]
That type of editorial response is fairly typical for the presubmission inquiries I've sent.  The editor gives some encouragement but hedges in case the full paper does not meet their expectations.  I can't think of many cases where an editor has been more enthusiastic or promised to send a submission to review, but that could just be me.

If you are still interested in this journal, you could make very light edits to the current draft to modify it for submission there.  Changing the title and removing "Tip <N>" from each subsection would be fast and sufficient to see whether they are interested in reviewing the full paper.

**Comment by rasbt** [comment]
I never sent presubmissions, but it is also what I kind of would have expected. Overall, it sounds like they want to keep options open. 

We could edit it as Tony suggested. In the scenario they send it out for peer-review, I think the challenge is that this is still a very unusual type of article (definitely not research, also not really review) and reviewers may not know what to do with it. When reviewing this article for PLoS, it would fitter into the 10 tips context and reviewers could existing 10 tips articles as a reference point for what to expect from this format.

**Comment by cgreene** [comment]
I have occasionally gotten a commitment to send a manuscript out for review via a presub inquiry, but usually when there's a preprint that I link to. I like this as a 10 tips at PLoS as a first strategy. We can pivot if needed later.

**Comment by rasbt** [comment]
> I like this as a 10 tips at PLoS as a first strategy. We can pivot if needed later.

Yeah. Especially since we have been working towards this format from the very beginning, I think this will make our lives easier. It would be nice to finally wrap this project up :).
