### ISSUE TITLE
Get rid of overfitting figure?

### ISSUE THREAD

**Issue by Benjamin-Lee** [Benjamin-Lee/deep-rules#280]
This figure has been a point of contention for a while. @SiminaB raised this concern (https://github.com/Benjamin-Lee/deep-rules/pull/275#discussion_r508919463):

> I'm not totally sure about this figure, just because even for linear regression, it's not recommended to use the predictions outside the range.

I seem to recall other people having various issues with it. I see several options:

1. Keep it as is
2. Add additional explanation to the figure caption
3. Change the figure
4. Eliminate the figure

I'm right now leaning towards eliminating it even though it was a good amount of work (trying various random seeds, polynomial degrees, etc) to make. Some reasons I think this is the best course of action are as follows:

1. It isn't actually an example of overfitting but rather a failure to generalize to out of range data. For DL models this distinction isn't always as clear cut (does showing x-rays from one hospital to a model trained at another count as out of range?) but for the linear regression it is.
2. There's nothing particularly novel about our figure showing overfitting. @rasbt has one in his excellent book and I'd rather point readers there.
3. If we do end up going with Nature Computational Science, xkcd style won't cut it.
4. It will possibly cause us issues down the line in review if we aren't very careful about how we describe the figure.

The main current upside is that it is only visual example we have in our paper. For visual people, figures/infographics can be quite helpful. 

If anyone is in favor of the figure, please do speak up.

**Comment by agitter** [comment]
I'm reopening this because I think the concern @SiminaB raised needs to be addressed before submission.  I like this figure.  However, I think the red points should lie within the range of the blue points.  We can also call them "Test data" instead of "Out-of-range data" to match the text better.

Can these red points be placed manually?  If the code used to generate the figure is shared, we could suggest the easiest way to modify it.

**Comment by Benjamin-Lee** [comment]
The code for generating the figure its over here: https://github.com/Benjamin-Lee/deep-rules/blob/master/content/images/overfitting.ipynb

I'm ok with these changes, especially since I too have reservations about the current figure.
