### ISSUE TITLE
Replace web links with peer-reviewed article references

### ISSUE THREAD

**Issue by rasbt** [Benjamin-Lee/deep-rules#304]
As discussed in #299, we should make a sweep through the article and see if the web links referencing newspaper/web articles can be replaced by references to peer-reviewed journals that have a permanent DOI.

**Comment by Benjamin-Lee** [comment]
I would also suggest changing the quotes if possible. In my training, I learned that direct quotes should only be used when the exact phrasing matters. For the quotes in that section, I don't think they require the exact wording.

**Comment by rasbt** [comment]
In general, you are correct. I think that using quotes for non-verbatim rephrasing would even be misleading and we should definitely avoid this. That being said, I am writing this in more general terms here, without context of the section. I can take a look at the PR to see if there was an issue with this.

**Comment by Benjamin-Lee** [comment]
Ok, I've removed the quotes while retaining the content in #306
