### ISSUE TITLE
Post manuscript as arXiv preprint

### ISSUE THREAD

**Issue by agitter** [Benjamin-Lee/deep-rules#365]
Now that version 1 has been submitted, I'd like to post it as a preprint on arXiv as well to share it more broadly and solicit feedback.  If no one objects, I can make the submission.  I should have time this weekend.

**Comment by rasbt** [comment]
Good idea! Thanks!

**Comment by agitter** [comment]
I submitted [`v1.0`](https://github.com/Benjamin-Lee/deep-rules/releases/tag/v1.0) to arXiv today.  It is scheduled to be announced at Tue, 1 Jun 2021 00:00:00 GMT.  I'll email the paper password to everyone after it posts.

**Comment by rasbt** [comment]
Great, thanks!
