### ISSUE TITLE
Don't share model weights trained on private data.

### ISSUE THREAD

**Issue by Benjamin-Lee** [Benjamin-Lee/deep-rules#4]
[Adversarial learning](https://en.wikipedia.org/wiki/Adversarial_machine_learning) (not to be confused with generative adversarial networks) is a growing threat. One particular issue is [model inversion](https://www.cs.cmu.edu/~mfredrik/papers/fjr2015ccs.pdf), which allows the extraction of sensitive data, either with or _without_ access to the weights. 

To be safe, unless you know what you are doing, it's probably best not to share weights that have been trained on sensitive data.

**Comment by cgreene** [comment]
Absolutely worth talking about, particularly in this domain. We can also discuss some techniques, like adding differential privacy during training, that might help mitigate some risks.

**Comment by evancofer** [comment]
@brettbj may have some good feedback here as well

This rule is clearly important (hence its inclusion via #61 ). I think it may ease adoption if we also add some actionable advice (e.g. commonly used software libraries, industry standards) in addition to a general precaution.

**Comment by rasbt** [comment]
Another relevant one (although not bio-specific):

- A generic framework for privacy preserving deep learning, https://arxiv.org/abs/1811.04017

**Comment by fmaguire** [comment]
Seems covered in tip 10 now https://github.com/Benjamin-Lee/deep-rules/blob/master/content/12.privacy.md
