### ISSUE TITLE
Test the robustness of your DL model in a simulation framework in which the ground truth is known

### ISSUE THREAD

**Issue by GreiffLab** [Benjamin-Lee/deep-rules#49]
**Have you checked the [list of proposed rules](https://github.com/Benjamin-Lee/deep-rules/issues?q=is%3Aissue+is%3Aopen+label%3Arule) to see if the rule has already been proposed?**

- [x] Yes

**Did you add yourself as a [contributor](https://github.com/Benjamin-Lee/deep-rules/blob/master/contributors.md) by making a pull request if this is your first contribution?**

- [x] Yes, I added myself or am already a contributor

Deep learning (DL) and generally machine learning on biological data suffers from the fact that the a priori ground truth remains unknown. Therefore, if available, a given DL architecture should be tested first on a simulation framework in which the different classes were explicitly modelled in order to understand strengths and weaknesses of the used DL model (robustness). The concept of stress testing the robustness of DL models is not unique to DL – however, given the complexity of DL, it is even more important in the context of DL.

**Comment by fmaguire** [comment]
Covered in https://github.com/Benjamin-Lee/deep-rules/blob/master/content/03.ml-concepts.md
