### ISSUE TITLE
Have an operational plan

### ISSUE THREAD

**Issue by pstew** [Benjamin-Lee/deep-rules#58]
**Have you checked the [list of proposed rules](https://github.com/Benjamin-Lee/deep-rules/issues?q=is%3Aissue+is%3Aopen+label%3Arule) to see if the rule has already been proposed?**

- [x] Yes

**Did you add yourself as a [contributor](https://github.com/Benjamin-Lee/deep-rules/blob/master/contributors.md) by making a pull request if this is your first contribution?**

- [x] Yes, I added myself or am already a contributor

**Feel free to elaborate, rant, and/or ramble.**

At the time of writing, [rules.md](https://github.com/Benjamin-Lee/deep-rules/blob/master/rules.md) is at 9 rules. How about a last rule that discusses some of the practical (operational/meta) considerations of ML/DL? Some ideas:

* Sure, #21 says "be reproducible", but how?! Some discussion of [Sacred](https://sacred.readthedocs.io/en/latest/) or similar is warranted. What is the "best" way for someone to save and share results? Can you upload a Python script and a flat file to github, or is it better to invest time in figuring out docker? What is docker, anyways?
* How do my analyses scale? I just learned about about MNIST on Kaggle and ran some DL on my personal laptop. Now I can scrape all of the [Gene Expression Omnibus](https://www.ncbi.nlm.nih.gov/geo/) and run some models, right?! 
* Does a newbie need to buy a fancy computer with 8 graphics cards? Can they just use their institution's HPC? What are the pros/cons for HPC vs cloud?
* Why is Python and/or R not good enough? Why on Earth would I want to use this Spark thing?

**Comment by agitter** [comment]
I edited the title to keep it focused on the rule instead of the numbering.
