### ISSUE TITLE
Moving forward (meta)

### ISSUE THREAD

**Issue by pstew** [Benjamin-Lee/deep-rules#64]
* Have we identified corresponding author(s) to help keep this on track and importantly pay the ~$2k USD publication fee?
* Should we agree on some timeline for getting the rules finalized and the presubmission inquiry sent in? Should the corresponding author(s) facilitate this?
* Will @Benjamin-Lee submit the presubmission inquiry? 
* If the presubmission inquiry goes well, then we should form a plan about who works on what or do we just see how it turns out? (some discussion in #48 about this)
* If the presubmission inquiry does not go well, then do we try a different journal with the same format or turn this into a review/primer or maybe a Methods in Molecular Biology chapter?
* Do some of the authors communicate offline? Some of you seem to work/have worked together on other projects. If so, can these communications/decisions be shared with us?

**Comment by agitter** [comment]
> Do some of the authors communicate offline? Some of you seem to work/have worked together on other projects. If so, can these communications/decisions be shared with us?

I advocate for keeping all the communications public on GitHub.  That keeps the project open and inclusive and also helps make everyone's contributions transparent.  At some point, journal communications will be made via email.  For the deep review, we posted most those as GitHub issues to keep all co-authors informed.

I personally do happen to know other contributors here from prior projects or affiliations but still plan to keep the manuscript discussion on GitHub.  Several of us know each other from the collaborative [deep review](https://github.com/greenelab/deep-review/).

**Comment by rasbt** [comment]
> I'm currently leaning towards using GH projects to track each rule's development. That way, we can use issues to track things to work on for each rule and use assignments to make sure that people know who is working on what.

that's sounds like a good idea. 

> I have no experience publishing book chapters, so expert guidance here is also welcome.

There are probably exceptions, but these are usually by invitation afaik.

> review/primer or maybe a Methods in Molecular Biology chapter?

Based on my experience writing for them they really want to be hands-on and have actionable examples (e.g, in this case usage instructions). We could do something like that but would probably make some substantial change.

Maybe we can worry about these things after the pre-submission  and pre-submission response :)

**Comment by agitter** [comment]
For deep review, we let authorship and the author roles evolve organically.  @cgreene was the initial corresponding author.  Over time, I helped more and he invited me to join as corresponding.  We didn't really plan it in advance.

This relates to another meta question of what this manuscript wants to do for author order.  There is only a little precedent for that with open collaborative manuscripts.  [Frassl et al.](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1006508#sec005) discusses this.  Options include ordering by contribution once the manuscript is done, random, semi-random (like deep review), alphabetical, etc.  I recommend letting the contributors decide what is fair (see https://github.com/greenelab/deep-review/issues/369).  

I'm not a fan of book chapters, especially for timely material like this.  They can take a very long time to appear because the book is only published once the slowest chapter authors return their material.  I'd prefer to explore other journals if it comes to that.

+1 for GitHub projects for the rules.

**Comment by Benjamin-Lee** [comment]
I personally don't have any strong feelings about author order determination, although I am in favor about doing it in a way in which the order is meaningful (_i.e._ by contributions or deep review-style semi-random).

One thing I do propose is making a table of contributors and their progress towards the [ICMJE requirements](http://icmje.org/recommendations/browse/roles-and-responsibilities/defining-the-role-of-authors-and-contributors.html) to keep track of authorship. Authors could PR their agreement to be accountable and their final approval, etc. What are thoughts on that?

**Comment by cgreene** [comment]
> One thing I do propose is making a table of contributors and their progress towards the ICMJE requirements to keep track of authorship. Authors could PR their agreement to be accountable and their final approval, etc. What are thoughts on that?

Big 👍 . Much easier to do during than after the fact.

**Comment by evancofer** [comment]
> I personally don't have any strong feelings about author order determination, although I am in favor about doing it in a way in which the order is meaningful (i.e. by contributions or deep review-style semi-random).

I support using semi-random ordering [in the style of deep review](https://github.com/greenelab/deep-review/issues/369).

>One thing I do propose is making a table of contributors and their progress towards the ICMJE requirements to keep track of authorship. Authors could PR their agreement to be accountable and their final approval, etc. What are thoughts on that?

I agree with @cgreen that this is a really good idea. I think it will help reduce the likelihood of authorship disputes as well.

**Comment by pstew** [comment]
Great, thanks for the responses everyone! I like the GH projects and random/semi-random authorship ideas.

@Benjamin-Lee 
Sure, a timeline might not be needed if you/corresponding author keep us on track. If there was to be a timeline, then I think it should along the lines of "hey let's try to finish the presubmission inquiry by the end of the year" instead of having hard deadlines for a volunteer project.

> Once we have the ten rules decided (which we're getting pretty close to finishing), I will send the inquiry. 

Who decides/how long? I think the last rule you added received good reception. Will you just give it a few days and see if anyone objects? I'm just trying to get a feel for the process. If you/the corresponding authors from Deep Review are keeping us on track, then I'll mellow out and not worry about it. 

@agitter 
Yeah, book chapter would definitely not be timely (I'm waiting on a chapter to be published for over a year now), but I just wanted to know what else the group was considering.

**Comment by rasbt** [comment]
> Who decides/how long? 

In the Education Articles section at https://journals.plos.org/ploscompbiol/s/other-article-types they say

>  Education articles should aim for 2000 and should not exceed 2500 words.

So each rule would roughly the length of a typical abstract (200-250 words)

**Comment by pstew** [comment]
@rasbt Sorry, to clarify I was referring who determines when it's ready and what kind of timeline.

**Comment by Benjamin-Lee** [comment]
> Sure, a timeline might not be needed if you/corresponding author keep us on track. If there was to be a timeline, then I think it should along the lines of "hey let's try to finish the presubmission inquiry by the end of the year" instead of having hard deadlines for a volunteer project.

As project lead, I'm doing my best to keep things moving at a reasonable pace. If things are going too slowly or quickly, I would highly appreciate feedback. 

> Who decides/how long? I think the last rule you added received good reception. Will you just give it a few days and see if anyone objects? I'm just trying to get a feel for the process. If you/the corresponding authors from Deep Review are keeping us on track, then I'll mellow out and not worry about it.

Precisely. We now have ten rules that I think everyone feels pretty good about (if not, make an issue!). If, in a few more days (say by Monday 12/3), there are no new PRs to rules.md and no new rule proposals that are dramatically different/warrant their own rule, then I will send out the inquiry and get to organizing the GH projects for each section. Once we see the pace of the writing, we'll be in a better place to come up with a timeline.

**Comment by agitter** [comment]
@Benjamin-Lee the pace has seemed good to me.  If it is much faster, then contributors may not have time to review proposed changes and provide input.  If it slows down, contributors will stray from the project.

For those of us on academic schedules, the break between semesters could be a good time to work on completing a first draft.

**Comment by beamandrew** [comment]
For those of us who have not participated in a distributed paper before and missed a lot of activity over the Thanksgiving holiday but would still like to contribute, what is a good way to get up to speed? Looking through the issues it's hard to tell where we are and what sections need the most work.

**Comment by julianstanley** [comment]
> For those of us who have not participated in a distributed paper before and missed a lot of activity over the Thanksgiving holiday but would still like to contribute, what is a good way to get up to speed? Looking through the issues it's hard to tell where we are and what sections need the most work.

This'll be better answered by someone like @Benjamin-Lee, @cgreene, or @agitter, but I'll give it a shot:

We have [10 rules drafted and pushed](https://github.com/Benjamin-Lee/deep-rules/blob/master/rules.md) but they're not finalized yet. I think that it would be useful to look over those rules and see if there's anything you think should be revised, added/removed, etc. before we get more committed (per @Benjamin-Lee's last comment on this thread).

I think that the actual writing hasn't begun yet, since we're waiting a few days before finalizing the outline. So as far as which sections need the most work: all of them. 

@cgreene mentioned at one point:
> From our experience with the deep learning review, I would imagine that divide to conquer, review and refine, divide, refine is one path to a document.

So I suspect that, if there's a rule or two that you feel especially passionate about, it would be appropriate to draft a 200-250 word commentary of that rule (per @rasbt's estimate) and put it up as an issue or a pull request

**Comment by AlexanderTitus** [comment]
Semi-random author order like the previous deep-review make the most sense to me. 

> I support using semi-random ordering [in the style of deep review](https://github.com/greenelab/deep-review/issues/369). I think it will help reduce the likelihood of disputes over author ordering.
