### ISSUE TITLE
Rule 2 is not a "rule"

### ISSUE THREAD

**Issue by Benjamin-Lee** [Benjamin-Lee/deep-rules#69]
My issue is with the title of the rule, not the content itself. Can we come up with a better title than:

`Rules more specific for DL (not necessarily ML) that apply to "DL in Biology" as well`

**Comment by rasbt** [comment]
Yeah, this was just a placeholder :)

Some initial suggestions:

1. Acquire the General Know-how of Deep Neural Network Training
2. Utilize the Tricks of the Trade when Applying to Deep Learning in Biology
3. Understand the Complexity of Training Deep Neural Networks

**Comment by Benjamin-Lee** [comment]
#3 is just what I was looking for! Thanks!
