### ISSUE TITLE
Tutorial demonstrating a "proper" DL workflow

### ISSUE THREAD

**Issue by evancofer** [Benjamin-Lee/deep-rules#88]
In the review from #59 , the authors included a [notebook](https://github.com/abidlabs/deep-learning-genomics-primer/blob/master/A_Primer_on_Deep_Learning_in_Genomics_Public.ipynb) illustrating a prototypical DL workflow for regulatory genomics. I found this to be a nice addition to that review. It might be interesting to implement a similar notebook for this paper, showing a sort of step-by-step DL application that uses or demonstrates all of the 10 rules. I would envision this as being a sort of online supplement to the article itself. As such, I am hoping that this issue will initiate a discussion of such a supplement, and what it might include.

**Comment by Benjamin-Lee** [comment]
Closing due to lack of interest. If anyone wants to work on this (as well as maintain it), feel free to reopen and we can discuss.
